//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogAppV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contiene
    {
        public int CodContiene { get; set; }
        public int CodCategoria { get; set; }
        public int CodPost { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}
